<a href="https://colab.research.google.com/github/maklybae/minor-intel/blob/main/intro-ds/seminars/sem01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Семинар 1: знакомство с NumPy


## Немного про Jupyter notebook

Полная документация: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

---
В Jupyter Notebook есть два режима работы: режим _команд_ и режим _редактирования_

_Командный_ режим нужен для того, чтобы взаимодействовать и управлять ячейками (добавлять, удалять, запускать, копировать, ...)

В режиме _редактирования_ вы меняете содержимое ячейки.

Ячейки бывают двух основных типов, _код_ и _разметка_

### Полезные команды

(находясь в командном режиме)

- `a` - добавить пустую ячейку сверху

- `b` - добавить пустую ячейку снизу
- `c` - скопировать текущую ячейку
- `v` - вставить скопированную ячейку
- `d` - удалить текущую ячейку
- `x` - вырезать (удалить и скопировать) текущую ячейку
- `m` - изменить тип выбранной ячейки на "разметка"
- `y` - изменить тип выбранной ячейки на "код"
- `z` - отменить последнее действие


- `Enter` - начать редактировать выбранную ячейку

(будучи в режим редактирования ячейки)
- `esc` - вернуться в командный режим

(будучи в любом режиме)

- `Ctrl + Enter` - запустить выбранную ячейку
- `Shift + Enter` - запустить выбранную ячейку и выбрать следующую

In [ ]:
2 + 2

5

## numpy

- документация: http://www.numpy.org/

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [1]:
import numpy as np

In [3]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [6]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


С чем мы работаем?

In [8]:
vec.dtype

dtype('int64')

In [9]:
type(vec)

numpy.ndarray

Размер массива:

In [10]:
vec.shape

(3, 2)

Число осей:

In [11]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [12]:
np.sum(vec)

21

In [13]:
np.sum(vec, axis=0)

array([ 9, 12])

In [14]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [15]:
vec.sum()

21

Транспонируем массив:

In [16]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [17]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [18]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [19]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
vec.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

Индексирование:

In [22]:
vec[:, 1]

array([2, 4, 6])

In [23]:
vec[2, :]

array([5, 6])

In [24]:
vec[1:2, 0]

array([3])

In [25]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

И, наконец - арифметические операции!

In [26]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [27]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [28]:
vec**2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [29]:
vec + vec**2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [30]:
vec * vec**2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [31]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [33]:
vec.T.dot(vec**2)

array([[153, 232],
       [188, 288]])

In [34]:
vec.dot((vec**2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [35]:
vec @ (vec**2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [36]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [38]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Булевы массивы:

In [39]:
is_even = vec % 2 == 0
print(is_even)

[[False  True]
 [False  True]
 [False  True]]


In [40]:
np.sum(is_even)

3

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [41]:
vec[vec % 2 == 0]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [42]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [43]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [44]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [45]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
np.hstack((vec, np.zeros(vec.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [47]:
np.vstack((vec, np.zeros(vec.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Генерация случайных чисел:

In [48]:
np.random.rand(2, 3)

array([[0.90483811, 0.62118851, 0.43516084],
       [0.74821148, 0.0426567 , 0.98496249]])

In [49]:
np.random.seed(2019)
np.random.rand(2, 3)

array([[0.90348221, 0.39308051, 0.62396996],
       [0.6378774 , 0.88049907, 0.29917202]])

In [50]:
np.random.randn(3, 2)

array([[ 0.57376143,  0.28772767],
       [-0.23563426,  0.95349024],
       [-1.6896253 , -0.34494271]])

In [51]:
np.random.normal(2, 1, size=3)

array([2.0169049 , 1.48501648, 2.24450929])

In [52]:
np.random.randint(5, 10, size=3)

array([8, 6, 8])

Почему вообще используют `numpy`?

In [53]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [54]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

CPU times: user 29.9 s, sys: 42.9 ms, total: 30 s
Wall time: 33 s


In [55]:
%%time
C = A @ B

CPU times: user 7.06 ms, sys: 1.01 ms, total: 8.07 ms
Wall time: 16.1 ms


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [70]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [71]:
# 1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).

arr[::-1]

array([4, 3, 2, 1, 0])

In [76]:
# 2. Найти максимальный нечетный элемент в массиве.

arr[arr % 2 == 1].max()

3

In [77]:
# 3. Замените все нечетные элементы массива на ваше любимое число.

arr[arr % 2 == 1] = 101
arr

array([  0, 101,   2, 101,   4])

In [79]:
# 4. Создайте массив первых n нечетных чисел, записанных в порядке убывания.
# Например, если n=5, то ответом будет array([9, 7, 5, 3, 1]).
# Функции, которые могут пригодиться при решении: .arange()

n = 5
odd_arr = np.arange(2 * n - 1, 0, -2)
odd_arr

array([9, 7, 5, 3, 1])

In [82]:
# 5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел.
# Например, если на вход поступают массив array([0, 1, 2, 3, 4]) и число 1.33, то ответом будет (1, 4).
# Функции, которые могут пригодиться при решении: .abs(), .argmax(), .argmin()

arr = np.arange(5)
request = 1.33
arr[np.argmin(np.absolute(arr - request))], arr[np.argmax(np.absolute(arr - request))]

(1, 4)

In [92]:
# 6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число).
# Например, если на вход поступает массив коэффициентов array([4, 6, 0, 1]), что соответствует полиному  4𝑥3+6𝑥2+1 ,
# на выходе получается массив коэффициентов array([1, 2, 0, 1, -2]), соответствующий полиному  𝑥4+2𝑥3+𝑥−2 . Функции, которые могут пригодиться при решении: .append()

coef = np.array([4, 6, 0, 1])
exponents = np.arange(len(coef) - 1, -1, -1)

antiderivative = np.append(coef / (exponents + 1), -2)
antiderivative

array([ 1.,  2.,  0.,  1., -2.])

In [94]:
# 7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

# будем рассматривать полином с коэффициентами из antiderivative
exponents = np.arange(len(antiderivative) - 1, -1, -1)

# нахождение производной от начального полинома с коэффициентами из coef
derivative = exponents[:-1] * antiderivative[:-1]
derivative

array([4., 6., 0., 1.])

In [99]:
# подстановка значений
x = 2
x_exponents = x ** exponents[1:] # степень производной меньше на 1

print(x_exponents)
derivative * x_exponents

[8 4 2 1]


array([32., 24.,  0.,  1.])